export const SET_STATUS_BAR_HEIGHT = 'SET_STATUS_BAR_HEIGHT'

export const SET_SHEET_DATA = 'SET_SHEET_DATA'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_PALYLIST = 'SET_PALYLIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'